### ISSUE TITLE
On the PAEA part it is hard to tell what enrichment analysis was performed

### ISSUE THREAD

**Issue by MaayanLab** [nasb-course/nasb-microtask-viewer-shiny#12]
Everything works very well, but once arriving to the PAEA part, it is hard to figure out what exactly the results represent... or what enrichment analysis was actually ran...

There are various outputs that can be generated:

up (input) vs. up (library), up (input) vs. down (library)
down (input) vs. up (library), down (input) vs. down (library)

and max similarity and max reversal by combining the ups and downs together...
this can be computed in various ways... one way is to used a signed version of the Jaccard, but maybe more sophisticated ways that are based on PAEA are probably better...

The network figure that attempts to visualize this is not that clear... one suggestion is to show the various "formulas" of the inputs and output with arrows, i.e., up regulated input genes shown in with the letter i and an arrow that points up...

**Comment by zero323** [comment]
This is actually true for both Characteristic Direction and PAEA. We can even change parameters but dispalyed results stay the same. I guess we can store this information next to chdir/paea results. Then we can display it next to actual results. 

I think it could be useful to include this information as a comment in exported data as well.  Maybe with checksum of the input file, application version, database version. Otherwise output is simply a bunch of names and numbers. 

Regarding  enrichment analysis and results presentation. Should we create predifined worfkflow and join result by default or focus on a flexibility and left decissions to the user? 

There are two more possible outputs: up (input) vs. all (library) and down (input) vs. all (library).  I am not sure if it even makes sense to give join option here.

Could you provide some sketch of the graph you have in mind?

**Comment by MaayanLab** [comment]
I think we figured out what is missing... PAEA only provides aligned gene sets, but I think what is needed is a search for the most orthogonal gene sets... This will require some edits of the PAEA library... Does that make sense?

**Comment by MaayanLab** [comment]
The input can be always the ChrDir, the output however can be aligned sets, orthogonal sets, and aligned or orthogonal set pairs...

**Comment by MaayanLab** [comment]
I was thinking about this more and I think the following will cover all the useful possibilities:

in↑ ∩ lib↑
in↓ ∩ lib↓
in↑ ∩ lib↓
in↓ ∩ lib↑
in↑ ∩ lib↑ + in↓ ∩ lib↓
in↑ ∩ lib↓ + in↓ ∩ lib↓ 
in↑ ∩ lib↑ + in↓ ∩ lib↓ - in↑ ∩ lib↓ - in↓ ∩ lib↓ 
in↑ ∩ lib↓ + in↓ ∩ lib↓ - in↑ ∩ lib↓ - in↓ ∩ lib↓

**Comment by zero323** [comment]
So we want to hide internal workflow from users, am I right?  We no longer provide intermediate results (like enriched downregulated/upregulated sets) and separate downloads and we give user, a single logical view of the results. 

Internally, each in\* ∩ lib\* is a single PAEA run and each +/- represents join operation. Lets say we use following scheme in↑ ∩ lib↓ + in↓ ∩ lib↓ - in↑ ∩ lib↓ - in↓ ∩ lib↓, then we execute PAEA four times
- p1 = in↑ ∩ lib↓
- p2 = in↓ ∩ lib↓
- p3 = in↑ ∩ lib↓
- p4 = in↓ ∩ lib↓

where each p\* gives us some geo_id, score (and some other fields). Then we join results by geo_id and order by combined score. 

```
p1 join p2 by geo_id %>%
    join p3 by geo_id %>%
    join p4 by geo_id %>%
order by p1.score + p2.score - p3.score - p4.score
```

Instead of describing internals we can give user options like:
- find sets with similar up-regulation patterns
- find sets with similar down-regulation patterns
- find sets with potential to reverse up-regulation 
- find sets with potential to reverse down-regulation 
- and so on ...

I am not sure if I understand the last three options. Did you mean?

in↑ ∩ lib↓ + in↓ ∩ lib↑
in↑ ∩ lib↑ + in↓ ∩ lib↓ - in↑ ∩ lib↓ - in↓ ∩ lib↑ 
in↑ ∩ lib↓ + in↓ ∩ lib↑ - in↑ ∩ lib↑ - in↓ ∩ lib↓

**Comment by zero323** [comment]
I don't understand the idea of searching for the most orthogonal gene sets.

Lets say we have two experiments (A, B) and measure only 2 probes (g1 and g2). If data is distributed as below I would expect to get characteristic direction coefficients (g1: 0, g2: 1) and (g1: 1, g2: 0) for A and B respectively. It looks like a clear example of the orthogonal sets. 

If we expect conditions to be similar at the expression level and we get results like this it could be interesting infromation otherwise it doesn't look particularly exciting.

![orthogonal](https://cloud.githubusercontent.com/assets/1554276/6403764/f6d4c766-be11-11e4-9b1d-79a48ccf5049.png)

**Comment by MaayanLab** [comment]
I like how you broke down the problem to compute p1, p2, p3 and p4 and then the other parts...
People really like to have the "intermediate results (like enriched downregulated/upregulated sets)" so please keep them... This is correct (I made some typos):
in↑ ∩ lib↓ + in↓ ∩ lib↑
in↑ ∩ lib↑ + in↓ ∩ lib↓ - in↑ ∩ lib↓ - in↓ ∩ lib↑
in↑ ∩ lib↓ + in↓ ∩ lib↑ - in↑ ∩ lib↑ - in↓ ∩ lib↓ 
The orthogonal issue is no longer relevant once we have this solution... sorry for the confusion... 

I think the orthogonal idea makes sense when you have the same controls and you look for perturbations that hit two completely different pathways...

**Comment by zero323** [comment]
For a last couple of days I've been trying to figure out how to handle this and I have basic solution.

First of all the parameters are stored and passed downstream so it should be clear what is the input and which transformations have been applied. It is not pretty but should work for now.

I am still not sure how to handle different paea options. Right now it doesn't really matter which one we run. There are only four basic options so we can run all of these once and combine results based on user choice. Since we don't have good scoring strategy for combined results I apply filters on p-values. I thought about using Jaccard similarity like you suggested but it mean that we almost completely discard paea results. I have some idea how to reuse principal angles but considering problems I reported to Neil it will have to wait.
